CREATE DATABASE BDVentas
ON PRIMARY
(NAME='BDVentas', FILENAME='D:\MSSQL\DATA\BDVentas.mdf',
SIZE =8Mb, FILEGROWTH=20%
),
FILEGROUP DATA DEFAULT
(NAME='BDVentas_Data', FILENAME='D:\MSSQL\DATA\BDVentas_Data.ndf',
SIZE =8Mb, FILEGROWTH=20%
)
LOG ON
(NAME='BDVentas_Log', FILENAME='D:\MSSQL\LOG\BDVentas_Log.ldf',
SIZE =8Mb, FILEGROWTH=20%
)
GO

-- CÉSAR OVIDIO MARTÍNEZ CHICAS | CREACIÓN DE UNA BASE DE DATOS CON BUENAS PRÁCTICAS HACIENDO USO DE FILEGROUPS