--PASO 1: 
--COMANDO PARA VER LO QUE NECECITA CADA BASE DE DATOS
SELECT LOG_REUSE_WAIT_DESC,*FROM SYS.DATABASES
WHERE NAME IN ('TSQL2017', 'APR3NDEDB', 'SISTEMA_BANCARIO', 'SISTEMA_TEL', 'SSISDB5')
GO

--VERIFIQUE EL TAMAÑO DE SU LOG
DBCC SQLPERF (LOGSPACE)

--PASO 2:
--COMPRIMIR EL LOG DE UNA BASE DE DATOS. DE SER NECESARIO
--SACAR BACKUP de LOG + Compresión, en Task -> Backup -> Backup Options
--        Seleccionar Aceptar.

--SCRIPT DE LA INSTRUCCION:
BACKUP LOG SISTEMA_TEL 
TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.PRODUCCION\MSSQL\Backup\LOG2_SISBANCA' 
WITH NOFORMAT, NOINIT,  NAME = N'SISTEMA_BANCARIO-Full Database Backup', 
SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 1
GO

--PASO 2: 
--DEFINIR LA COMPRESION DEL LOG DE LA DATA. -> DATABASE -> PROPERTIES -> FILES
--CALCULE EL 40% DEL ROWS DATA
--CALCULAR EL 40% DE LA COMPRESION -FORMULA: DATA * .40
--COLOQUE EL RESULTADO EN LOG.
--Seleccionar Aceptar

--SCRIPT DE LA INSTRUCCION:
USE [SISTEMA_BANCARIO]
GO
DBCC SHRINKFILE (N'SISTEMA_BANCARIO_log' , 28)
GO
USE [master]
GO

--PASO 3: 
--VERIFIQUE EL TAMAÑO DE SU LOG
DBCC SQLPERF (LOGSPACE)