USE master
GO

CREATE MASTER KEY ENCRYPTION BY PASSORD = 'A123456789$b'
GO

CREATE CERTIFICATE MyCertificadoTDE WITH SUBJECT = 'My DEJ Certificate'
GO

USE TSQL2017
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE MyCertificadoTDE
GO

ALTER DATABASE TSQL2017
SET ENCRYPTION ON
GO