ALTER DATABASE SISTEMA_BANCARIO ADD FILEGROUP GRUPODATA1
ALTER DATABASE SISTEMA_BANCARIO ADD FILEGROUP GRUPODATA2
-- UNA TABLA SE ALMACENA EN UN ARCHIVO
ALTER DATABASE SISTEMA_BANCARIO
ADD FILE(
         NAME = DATASEC1,
		 FILENAME = 'C:\data\DATASEC1.ndf',
		 SIZE = 1MB,
		 MAXSIZE = 20MB,
		 FILEGROWTH = 1MB
		 )
TO FILEGROUP GRUPODATA1
-- UNA TABLA SE ALMACENA EN OTRO ARCHIVO
ALTER DATABASE SISTEMA_BANCARIO
ADD FILE(
         NAME = DATASEC2,
		 FILENAME = 'C:\data\DATASEC2.ndf',
		 SIZE = 1MB,
		 MAXSIZE = 20MB,
		 FILEGROWTH = 1MB
		 )
TO FILEGROUP GRUPODATA2