/* 
======================================================================
Elaborado por: César Ovidio Martínez Chicas
Fecha creación: 28/04/2024
Ejercicio: N°1

Clase recibida: N°3
Módulo #1: Analista de Base de datos con SQL Server

1.-ENCONTRAR LA ÚLTIMA VENTA REALIZADA POR CADA EMPLEADO 
======================================================================
*/

--MÉTODO #1
SELECT *
FROM SALES.ORDERS AS EXTERNA
WHERE ORDERDATE = (
    SELECT MAX(ORDERDATE) -- Subconsulta autocontenida
    FROM SALES.ORDERS AS INTERNA
    WHERE EXTERNA.EMPID = INTERNA.EMPID
)
ORDER BY EXTERNA.EMPID ASC;
GO

--MÉTODO #2
SELECT *
FROM SALES.ORDERS AS EXTERNA
WHERE ORDERDATE =
          (SELECT MAX(ORDERDATE) -- SUB CONSULTA CORRELACIONADA
		  FROM SALES.ORDERS AS INTERNA
		  WHERE EXTERNA.EMPID=INTERNA.EMPID)
ORDER BY EXTERNA.EMPID ASC
GO

--MÉTODO #3
SELECT EXTERNA.*
FROM SALES.ORDERS AS EXTERNA
INNER JOIN (            --UTILIZANDO INNER JOINN SOBRE SUB CONSULTA CORRELACIONADA
    SELECT EMPID, MAX(ORDERDATE) AS MAX_ORDERDATE
    FROM SALES.ORDERS
    GROUP BY EMPID
) AS INTERNA ON EXTERNA.EMPID = INTERNA.EMPID AND EXTERNA.ORDERDATE = INTERNA.MAX_ORDERDATE
ORDER BY EXTERNA.EMPID ASC;
GO