SELECT SUBSTRING(SITUACION_TRIBUTARIA,10,9)AS SitSubString,
SUBSTRING(COD_CONTRIBUYENTE,16,5)AS CodContribuyente,
RIGHT(SITUACION_TRIBUTARIA,9)AS SitRight,
LEFT(SITUACION_TRIBUTARIA,8)AS SitLeft,
LEN(COD_CONTRIBUYENTE)AS NroCaracteres,
DATALENGTH(UBIGEO) AS UbigeoBytes,
DATALENGTH(SITUACION_TRIBUTARIA)AS SitBytes,
REPLACE(SECTOR_FISCAL,'Urb.','Urbanizacion')AS SectorFiscal,
REPLICATE('0',2)+SUBSTRING(COD_CONTRIBUYENTE,16,5) NewCodCtrByte,
LOWER(DEPARTAMENTO)AS NewDpto,'   75FB31   ' AS Valor,
RTRIM(LTRIM('   75FB31   '))AS NewValor,*
FROM TRIBUTOS
WHERE ANIO_DEUDA=2023 AND RIGHT(SITUACION_TRIBUTARIA,9)<>'ordinaria'
AND LEN(COD_CONTRIBUYENTE)<>34