-- SCRIPT PARA CREAR UN OLTP EN UNA BASE --
/* CREAR UNA BASE DE DATOS CON TABLAS OPTIMIZADAS OLTP */

-- CONFIGURAR EL NIVEL DE AISLAMIENTO PARA TABLAS OPTIMIZADAS PARA MEMORIA EN INSTANTÁNEA
ALTER DATABASE RRHH SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON
GO

-- AÑADIR GRUPO DE ARCHIVOS OPTIMIZADO PARA MEMORIA A LA BASE DE DATOS
ALTER DATABASE RRHH ADD FILEGROUP RRHH_mofg CONTAINS MEMORY_OPTIMIZED_DATA
GO

-- AÑADIR ARCHIVO DE OBJETOS OPTIMIZADOS PARA MEMORIA
-- PUEDES ESTABLECER CUALQUIER RUTA QUE QUIERAS - EN ESTE EJEMPLO: D:MEMOPTDATA
-- SI EL DIRECTORIO D:\DEMOS\MEMOPTDATA NO EXISTE, TENDRÁS QUE CREAR SI (O UTILIZAR OTRA CARPETA)
ALTER DATABASE RRHH ADD FILE (NAME = 'RRHH_mofg',
FILENAME = 'C:\DEMOS\MEMOPTDATA\RRHH_mofg') TO FILEGROUP RRHH_mofg
GO