-- ¿Cómo puedo implementar ISOLATION LEVEL a nivel procedimiento?

 CREATE PROCEDURE MySP AS BEGIN SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED BEGIN TRAN SELECT * FROM MyTable SELECT * FROM MyTable2 SELECT * FROM MyTable3 COMMIT TRAN END
-- ¿Como puedo implementar ISOLATION LEVEL solo en la ejecución del procedimiento?

 SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
 EXEC [sp_GetProductDetails] 'ABCD' , '2017-02-20T11:51:37.3178768'
