-- © 2023 César Martínez Engineer. All Copyright
-- CREADOR DEL CODIGO T-SQL -> CÉSAR OVIDIO MARTÍNEZ CHICAS.
-- SCRIPT PARA CREAR UN MIRRORING EN UN ENTORNO DE ALTA DISPONIBILIDAD DE SQL SEREVR.

-- EJECUCIÓN DE UN MIRRORING --

-- HAY QUE TOMAR EN CUENTA QUE PARA RALIZAR ESTOS PASOS PRIMERO HAY QUE TENER
-- NUESTRO FULL.BAK Y LOG.BAK DE NUESTRA BASE DE DATOS, PARA COMPARTIRLA Y 
-- RESTAURARLA EN NUESTRA MAQUINA SECUNDARIA.

-- PRIMERO EL FULL Y LUEGO SE LE RESTAURA A LA BASE DE DATOS EL LOG DE TRANSACCIONES
-- LUEGO EN EL SEVIDOR PRIMARIO SE REALIZAR EL INTENTO DE CREACIÓN DEL MIRRORING
-- DE FORMA MANUAL, PARA ASIGNAR LOS PUERTOS DE CARA NODO Y EL NOMBRE DEL MIRRORING.

-- EN MI CASO LE ASIGNE A MI NODO PRIMARIO EL PUERTO 5022 CON EL NOMBRE DE MIRRORING 1.
-- Y A MI NODO SECUNDARIO EL PUERTO 5023 CON EL NOMBRE DE MIRRORING 2.

-- TENIENDO HECHO ESO, LANZARA ALGÚN ERROR YA SEA EL 1428 0 927.
-- IGUALMENTE HAY QUE FINALIZARLO.

-- POSTERIOR A ESO SE EJECUTARÁN LOS SIGUIENTES COMANDOS:

-- PASO 1 
-- EJECUTAR CÓDIGO EN SERVIDOR SECUNDARIO --

-- 1 
ALTER DATABASE [DATA BASE] SET PARTNER OFF
GO

-- 2
ALTER DATABASE [DATA BASE] SET PARTNER = 'TCP://INSTANCIA NODO SECUNDARIO:5023'
GO

-- 3
ALTER DATABASE [DATA BASE] SET PARTNER OFF
GO

-- 4
ALTER DATABASE [DATA BASE] SET PARTNER = 'TCP://IP NODO PRIMARIO:5022'
GO

-- PASO 2
-- EJECUTAR CÓDIGO EN SERVIDOR PRIMARIO --

--1
ALTER DATABASE [DATA BASE] SET PARTNER = 'TCP://192.168.0.9:5023';
GO

-- 2
GRANT CONNECT ON ENDPOINT:: Mirroring1 TO [NT AUTHORITY\SYSTEM]
GO

-- PASO 3
-- EJECUTAR CÓDIGO EN SERVIDOR SECUNDARIO --

-- 1
GRANT CONNECT ON ENDPOINT:: Mirroring2 TO [NT AUTHORITY\SYSTEM]
GO
